// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsAlarmApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashAlarmApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsAlarmApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsAlarmApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsAlarmApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsAlarmApi(lhsKey, rhsKey) {
          if deepEqualsAlarmApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsAlarmApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashAlarmApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashAlarmApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashAlarmApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashAlarmApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashAlarmApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashAlarmApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// One concrete future firing, as handed to the platform scheduler.
/// [fireAtEpochMs] is absolute UTC milliseconds — all wall-clock and DST
/// reasoning happens in Dart before this crosses the channel.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAlarm: Hashable {
  var id: Int64
  var fireAtEpochMs: Int64
  var label: String
  var soundAsset: String
  var vibrate: Bool
  /// Vibration pattern key: 'gentle' | 'standard' | 'intense'. Only meaningful
  /// while [vibrate] is true. Unknown values fall back to 'standard' on the
  /// platform side, so a newer Dart never breaks an older native build.
  /// iOS ignores this — notification vibration is not customizable there.
  var vibrationPattern: String
  /// Recurrence pattern, for platforms that own recurrence natively (iOS
  /// AlarmKit / UNCalendar). [weekdays] uses 0=Sun…6=Sat; empty = one-shot.
  /// Android ignores these and schedules the single [fireAtEpochMs] instant.
  var hour: Int64
  var minute: Int64
  var weekdays: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAlarm? {
    let id = pigeonVar_list[0] as! Int64
    let fireAtEpochMs = pigeonVar_list[1] as! Int64
    let label = pigeonVar_list[2] as! String
    let soundAsset = pigeonVar_list[3] as! String
    let vibrate = pigeonVar_list[4] as! Bool
    let vibrationPattern = pigeonVar_list[5] as! String
    let hour = pigeonVar_list[6] as! Int64
    let minute = pigeonVar_list[7] as! Int64
    let weekdays = pigeonVar_list[8] as! [Int64]

    return NativeAlarm(
      id: id,
      fireAtEpochMs: fireAtEpochMs,
      label: label,
      soundAsset: soundAsset,
      vibrate: vibrate,
      vibrationPattern: vibrationPattern,
      hour: hour,
      minute: minute,
      weekdays: weekdays
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      fireAtEpochMs,
      label,
      soundAsset,
      vibrate,
      vibrationPattern,
      hour,
      minute,
      weekdays,
    ]
  }
  static func == (lhs: NativeAlarm, rhs: NativeAlarm) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAlarmApi(lhs.id, rhs.id) && deepEqualsAlarmApi(lhs.fireAtEpochMs, rhs.fireAtEpochMs) && deepEqualsAlarmApi(lhs.label, rhs.label) && deepEqualsAlarmApi(lhs.soundAsset, rhs.soundAsset) && deepEqualsAlarmApi(lhs.vibrate, rhs.vibrate) && deepEqualsAlarmApi(lhs.vibrationPattern, rhs.vibrationPattern) && deepEqualsAlarmApi(lhs.hour, rhs.hour) && deepEqualsAlarmApi(lhs.minute, rhs.minute) && deepEqualsAlarmApi(lhs.weekdays, rhs.weekdays)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAlarm")
    deepHashAlarmApi(value: id, hasher: &hasher)
    deepHashAlarmApi(value: fireAtEpochMs, hasher: &hasher)
    deepHashAlarmApi(value: label, hasher: &hasher)
    deepHashAlarmApi(value: soundAsset, hasher: &hasher)
    deepHashAlarmApi(value: vibrate, hasher: &hasher)
    deepHashAlarmApi(value: vibrationPattern, hasher: &hasher)
    deepHashAlarmApi(value: hour, hasher: &hasher)
    deepHashAlarmApi(value: minute, hasher: &hasher)
    deepHashAlarmApi(value: weekdays, hasher: &hasher)
  }
}

/// Everything that can silently stop Rise from ringing. Surfaced by the Setup
/// Guardian; re-checked on every app launch because OEMs revert these.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AlarmPermissions: Hashable {
  var notifications: Bool
  var exactAlarm: Bool
  var fullScreenIntent: Bool
  var batteryUnrestricted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AlarmPermissions? {
    let notifications = pigeonVar_list[0] as! Bool
    let exactAlarm = pigeonVar_list[1] as! Bool
    let fullScreenIntent = pigeonVar_list[2] as! Bool
    let batteryUnrestricted = pigeonVar_list[3] as! Bool

    return AlarmPermissions(
      notifications: notifications,
      exactAlarm: exactAlarm,
      fullScreenIntent: fullScreenIntent,
      batteryUnrestricted: batteryUnrestricted
    )
  }
  func toList() -> [Any?] {
    return [
      notifications,
      exactAlarm,
      fullScreenIntent,
      batteryUnrestricted,
    ]
  }
  static func == (lhs: AlarmPermissions, rhs: AlarmPermissions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAlarmApi(lhs.notifications, rhs.notifications) && deepEqualsAlarmApi(lhs.exactAlarm, rhs.exactAlarm) && deepEqualsAlarmApi(lhs.fullScreenIntent, rhs.fullScreenIntent) && deepEqualsAlarmApi(lhs.batteryUnrestricted, rhs.batteryUnrestricted)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AlarmPermissions")
    deepHashAlarmApi(value: notifications, hasher: &hasher)
    deepHashAlarmApi(value: exactAlarm, hasher: &hasher)
    deepHashAlarmApi(value: fullScreenIntent, hasher: &hasher)
    deepHashAlarmApi(value: batteryUnrestricted, hasher: &hasher)
  }
}

/// What a platform's alarm engine can do. iOS 16–25 has no system-alarm API,
/// so the sync service falls back to a notification burst there.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCapabilities: Hashable {
  /// True when the platform can schedule true system alarms (Android
  /// AlarmManager always; iOS only on 26+ via AlarmKit). False on iOS 16–25,
  /// where [AlarmHostApi.reconcileNotifications] is used instead.
  var supportsSystemAlarms: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCapabilities? {
    let supportsSystemAlarms = pigeonVar_list[0] as! Bool

    return PlatformCapabilities(
      supportsSystemAlarms: supportsSystemAlarms
    )
  }
  func toList() -> [Any?] {
    return [
      supportsSystemAlarms
    ]
  }
  static func == (lhs: PlatformCapabilities, rhs: PlatformCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAlarmApi(lhs.supportsSystemAlarms, rhs.supportsSystemAlarms)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCapabilities")
    deepHashAlarmApi(value: supportsSystemAlarms, hasher: &hasher)
  }
}

/// One scheduled local notification in the iOS 16–25 fallback burst. The Dart
/// budget allocator produces these; only the iOS notification engine consumes
/// them. Android reports [PlatformCapabilities.supportsSystemAlarms] true and
/// never receives these.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationRequest: Hashable {
  var alarmId: Int64
  var fireAtEpochMs: Int64
  var label: String
  var sound: String
  var burstIndex: Int64
  var burstTotal: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationRequest? {
    let alarmId = pigeonVar_list[0] as! Int64
    let fireAtEpochMs = pigeonVar_list[1] as! Int64
    let label = pigeonVar_list[2] as! String
    let sound = pigeonVar_list[3] as! String
    let burstIndex = pigeonVar_list[4] as! Int64
    let burstTotal = pigeonVar_list[5] as! Int64

    return NotificationRequest(
      alarmId: alarmId,
      fireAtEpochMs: fireAtEpochMs,
      label: label,
      sound: sound,
      burstIndex: burstIndex,
      burstTotal: burstTotal
    )
  }
  func toList() -> [Any?] {
    return [
      alarmId,
      fireAtEpochMs,
      label,
      sound,
      burstIndex,
      burstTotal,
    ]
  }
  static func == (lhs: NotificationRequest, rhs: NotificationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAlarmApi(lhs.alarmId, rhs.alarmId) && deepEqualsAlarmApi(lhs.fireAtEpochMs, rhs.fireAtEpochMs) && deepEqualsAlarmApi(lhs.label, rhs.label) && deepEqualsAlarmApi(lhs.sound, rhs.sound) && deepEqualsAlarmApi(lhs.burstIndex, rhs.burstIndex) && deepEqualsAlarmApi(lhs.burstTotal, rhs.burstTotal)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NotificationRequest")
    deepHashAlarmApi(value: alarmId, hasher: &hasher)
    deepHashAlarmApi(value: fireAtEpochMs, hasher: &hasher)
    deepHashAlarmApi(value: label, hasher: &hasher)
    deepHashAlarmApi(value: sound, hasher: &hasher)
    deepHashAlarmApi(value: burstIndex, hasher: &hasher)
    deepHashAlarmApi(value: burstTotal, hasher: &hasher)
  }
}

private class AlarmApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeAlarm.fromList(self.readValue() as! [Any?])
    case 130:
      return AlarmPermissions.fromList(self.readValue() as! [Any?])
    case 131:
      return PlatformCapabilities.fromList(self.readValue() as! [Any?])
    case 132:
      return NotificationRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AlarmApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeAlarm {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AlarmPermissions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCapabilities {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AlarmApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AlarmApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AlarmApiPigeonCodecWriter(data: data)
  }
}

class AlarmApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AlarmApiPigeonCodec(readerWriter: AlarmApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AlarmHostApi {
  /// Replaces the platform's entire scheduled set with [alarms].
  func reconcile(alarms: [NativeAlarm]) throws
  /// Rings [alarm] immediately without touching the scheduled set.
  ///
  /// Missed-alarm recovery must never go through [reconcile]: reconcile is a
  /// full replace, so recovering one alarm that way would silently cancel
  /// every other alarm the user has set.
  func ringNow(alarm: NativeAlarm) throws
  func cancelAll() throws
  func getPermissions() throws -> AlarmPermissions
  func requestNotificationPermission() throws
  func openExactAlarmSettings() throws
  func openBatterySettings() throws
  func openFullScreenIntentSettings() throws
  /// The alarm id currently ringing, or null if nothing is ringing.
  ///
  /// Safe to call repeatedly — this peeks, it does not clear state. The id
  /// stays valid for the whole ring so [stopRinging] can verify it is
  /// stopping the alarm it was asked to stop. This is the *only* way Dart
  /// learns what is ringing — there is no push channel the other way — so
  /// callers must poll it: at cold start (the ringing activity can launch
  /// the Flutter engine from scratch) and again on every app resume (the
  /// ringing activity is `singleInstance`, so a second alarm taking over an
  /// already-running engine delivers onNewIntent natively with no signal
  /// that reaches Dart on its own).
  func getRingingAlarmId() throws -> Int64?
  func stopRinging(alarmId: Int64) throws
  /// Signals that a headless reconcile (boot, app update, clock change) has
  /// finished, so the platform can tear down the engine that ran it.
  /// Harmless to call from a normal app engine, where it is a no-op.
  func reconcileFinished() throws
  /// What this platform's alarm engine supports. Queried by the sync service
  /// to choose between system alarms and the notification-burst fallback.
  func capabilities() throws -> PlatformCapabilities
  /// Replaces the platform's entire scheduled notification set (the iOS 16–25
  /// fallback). A full replace, like [reconcile]. No-op on Android.
  func reconcileNotifications(requests: [NotificationRequest]) throws
  /// Schedules the post-dismissal "still up?" check for [alarm]: a notification
  /// at [checkAtEpochMs] (absolute UTC ms) and, if the user does not confirm
  /// within 100s, a re-fire of [alarm] through the normal ring path. Android
  /// only for now; a no-op on platforms without the impl.
  func scheduleWakeCheck(alarm: NativeAlarm, checkAtEpochMs: Int64) throws
  /// Cancels any pending wake-check (notification + re-fire) for [alarmId].
  func cancelWakeCheck(alarmId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AlarmHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AlarmApiPigeonCodec.shared }
  /// Sets up an instance of `AlarmHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AlarmHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Replaces the platform's entire scheduled set with [alarms].
    let reconcileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.reconcile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reconcileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmsArg = args[0] as! [NativeAlarm]
        do {
          try api.reconcile(alarms: alarmsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reconcileChannel.setMessageHandler(nil)
    }
    /// Rings [alarm] immediately without touching the scheduled set.
    ///
    /// Missed-alarm recovery must never go through [reconcile]: reconcile is a
    /// full replace, so recovering one alarm that way would silently cancel
    /// every other alarm the user has set.
    let ringNowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.ringNow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      ringNowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmArg = args[0] as! NativeAlarm
        do {
          try api.ringNow(alarm: alarmArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      ringNowChannel.setMessageHandler(nil)
    }
    let cancelAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.cancelAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllChannel.setMessageHandler { _, reply in
        do {
          try api.cancelAll()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelAllChannel.setMessageHandler(nil)
    }
    let getPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.getPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPermissionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPermissions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPermissionsChannel.setMessageHandler(nil)
    }
    let requestNotificationPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.requestNotificationPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestNotificationPermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestNotificationPermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestNotificationPermissionChannel.setMessageHandler(nil)
    }
    let openExactAlarmSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.openExactAlarmSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openExactAlarmSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openExactAlarmSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openExactAlarmSettingsChannel.setMessageHandler(nil)
    }
    let openBatterySettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.openBatterySettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openBatterySettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openBatterySettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openBatterySettingsChannel.setMessageHandler(nil)
    }
    let openFullScreenIntentSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.openFullScreenIntentSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openFullScreenIntentSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openFullScreenIntentSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openFullScreenIntentSettingsChannel.setMessageHandler(nil)
    }
    /// The alarm id currently ringing, or null if nothing is ringing.
    ///
    /// Safe to call repeatedly — this peeks, it does not clear state. The id
    /// stays valid for the whole ring so [stopRinging] can verify it is
    /// stopping the alarm it was asked to stop. This is the *only* way Dart
    /// learns what is ringing — there is no push channel the other way — so
    /// callers must poll it: at cold start (the ringing activity can launch
    /// the Flutter engine from scratch) and again on every app resume (the
    /// ringing activity is `singleInstance`, so a second alarm taking over an
    /// already-running engine delivers onNewIntent natively with no signal
    /// that reaches Dart on its own).
    let getRingingAlarmIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.getRingingAlarmId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRingingAlarmIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getRingingAlarmId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getRingingAlarmIdChannel.setMessageHandler(nil)
    }
    let stopRingingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.stopRinging\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRingingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmIdArg = args[0] as! Int64
        do {
          try api.stopRinging(alarmId: alarmIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopRingingChannel.setMessageHandler(nil)
    }
    /// Signals that a headless reconcile (boot, app update, clock change) has
    /// finished, so the platform can tear down the engine that ran it.
    /// Harmless to call from a normal app engine, where it is a no-op.
    let reconcileFinishedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.reconcileFinished\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reconcileFinishedChannel.setMessageHandler { _, reply in
        do {
          try api.reconcileFinished()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reconcileFinishedChannel.setMessageHandler(nil)
    }
    /// What this platform's alarm engine supports. Queried by the sync service
    /// to choose between system alarms and the notification-burst fallback.
    let capabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.capabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      capabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.capabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      capabilitiesChannel.setMessageHandler(nil)
    }
    /// Replaces the platform's entire scheduled notification set (the iOS 16–25
    /// fallback). A full replace, like [reconcile]. No-op on Android.
    let reconcileNotificationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.reconcileNotifications\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reconcileNotificationsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestsArg = args[0] as! [NotificationRequest]
        do {
          try api.reconcileNotifications(requests: requestsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reconcileNotificationsChannel.setMessageHandler(nil)
    }
    /// Schedules the post-dismissal "still up?" check for [alarm]: a notification
    /// at [checkAtEpochMs] (absolute UTC ms) and, if the user does not confirm
    /// within 100s, a re-fire of [alarm] through the normal ring path. Android
    /// only for now; a no-op on platforms without the impl.
    let scheduleWakeCheckChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.scheduleWakeCheck\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scheduleWakeCheckChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmArg = args[0] as! NativeAlarm
        let checkAtEpochMsArg = args[1] as! Int64
        do {
          try api.scheduleWakeCheck(alarm: alarmArg, checkAtEpochMs: checkAtEpochMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      scheduleWakeCheckChannel.setMessageHandler(nil)
    }
    /// Cancels any pending wake-check (notification + re-fire) for [alarmId].
    let cancelWakeCheckChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.cancelWakeCheck\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelWakeCheckChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmIdArg = args[0] as! Int64
        do {
          try api.cancelWakeCheck(alarmId: alarmIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelWakeCheckChannel.setMessageHandler(nil)
    }
  }
}
