// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsAlarmApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashAlarmApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsAlarmApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsAlarmApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsAlarmApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsAlarmApi(lhsKey, rhsKey) {
          if deepEqualsAlarmApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsAlarmApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashAlarmApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashAlarmApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashAlarmApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashAlarmApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashAlarmApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashAlarmApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// One concrete future firing, as handed to the platform scheduler.
/// [fireAtEpochMs] is absolute UTC milliseconds — all wall-clock and DST
/// reasoning happens in Dart before this crosses the channel.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAlarm: Hashable {
  var id: Int64
  var fireAtEpochMs: Int64
  var label: String
  var soundAsset: String
  var vibrate: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAlarm? {
    let id = pigeonVar_list[0] as! Int64
    let fireAtEpochMs = pigeonVar_list[1] as! Int64
    let label = pigeonVar_list[2] as! String
    let soundAsset = pigeonVar_list[3] as! String
    let vibrate = pigeonVar_list[4] as! Bool

    return NativeAlarm(
      id: id,
      fireAtEpochMs: fireAtEpochMs,
      label: label,
      soundAsset: soundAsset,
      vibrate: vibrate
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      fireAtEpochMs,
      label,
      soundAsset,
      vibrate,
    ]
  }
  static func == (lhs: NativeAlarm, rhs: NativeAlarm) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAlarmApi(lhs.id, rhs.id) && deepEqualsAlarmApi(lhs.fireAtEpochMs, rhs.fireAtEpochMs) && deepEqualsAlarmApi(lhs.label, rhs.label) && deepEqualsAlarmApi(lhs.soundAsset, rhs.soundAsset) && deepEqualsAlarmApi(lhs.vibrate, rhs.vibrate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAlarm")
    deepHashAlarmApi(value: id, hasher: &hasher)
    deepHashAlarmApi(value: fireAtEpochMs, hasher: &hasher)
    deepHashAlarmApi(value: label, hasher: &hasher)
    deepHashAlarmApi(value: soundAsset, hasher: &hasher)
    deepHashAlarmApi(value: vibrate, hasher: &hasher)
  }
}

/// Everything that can silently stop Rise from ringing. Surfaced by the Setup
/// Guardian; re-checked on every app launch because OEMs revert these.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AlarmPermissions: Hashable {
  var notifications: Bool
  var exactAlarm: Bool
  var fullScreenIntent: Bool
  var batteryUnrestricted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AlarmPermissions? {
    let notifications = pigeonVar_list[0] as! Bool
    let exactAlarm = pigeonVar_list[1] as! Bool
    let fullScreenIntent = pigeonVar_list[2] as! Bool
    let batteryUnrestricted = pigeonVar_list[3] as! Bool

    return AlarmPermissions(
      notifications: notifications,
      exactAlarm: exactAlarm,
      fullScreenIntent: fullScreenIntent,
      batteryUnrestricted: batteryUnrestricted
    )
  }
  func toList() -> [Any?] {
    return [
      notifications,
      exactAlarm,
      fullScreenIntent,
      batteryUnrestricted,
    ]
  }
  static func == (lhs: AlarmPermissions, rhs: AlarmPermissions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsAlarmApi(lhs.notifications, rhs.notifications) && deepEqualsAlarmApi(lhs.exactAlarm, rhs.exactAlarm) && deepEqualsAlarmApi(lhs.fullScreenIntent, rhs.fullScreenIntent) && deepEqualsAlarmApi(lhs.batteryUnrestricted, rhs.batteryUnrestricted)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AlarmPermissions")
    deepHashAlarmApi(value: notifications, hasher: &hasher)
    deepHashAlarmApi(value: exactAlarm, hasher: &hasher)
    deepHashAlarmApi(value: fullScreenIntent, hasher: &hasher)
    deepHashAlarmApi(value: batteryUnrestricted, hasher: &hasher)
  }
}

private class AlarmApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeAlarm.fromList(self.readValue() as! [Any?])
    case 130:
      return AlarmPermissions.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AlarmApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeAlarm {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AlarmPermissions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AlarmApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AlarmApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AlarmApiPigeonCodecWriter(data: data)
  }
}

class AlarmApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AlarmApiPigeonCodec(readerWriter: AlarmApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AlarmHostApi {
  /// Replaces the platform's entire scheduled set with [alarms].
  func reconcile(alarms: [NativeAlarm]) throws
  /// Rings [alarm] immediately without touching the scheduled set.
  ///
  /// Missed-alarm recovery must never go through [reconcile]: reconcile is a
  /// full replace, so recovering one alarm that way would silently cancel
  /// every other alarm the user has set.
  func ringNow(alarm: NativeAlarm) throws
  func cancelAll() throws
  func getPermissions() throws -> AlarmPermissions
  func requestNotificationPermission() throws
  func openExactAlarmSettings() throws
  func openBatterySettings() throws
  func openFullScreenIntentSettings() throws
  /// The alarm id currently ringing, consumed exactly once. Covers cold start:
  /// the ringing activity can launch the Flutter engine from scratch.
  func consumeFiredAlarmId() throws -> Int64?
  func stopRinging(alarmId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AlarmHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AlarmApiPigeonCodec.shared }
  /// Sets up an instance of `AlarmHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AlarmHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Replaces the platform's entire scheduled set with [alarms].
    let reconcileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.reconcile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reconcileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmsArg = args[0] as! [NativeAlarm]
        do {
          try api.reconcile(alarms: alarmsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reconcileChannel.setMessageHandler(nil)
    }
    /// Rings [alarm] immediately without touching the scheduled set.
    ///
    /// Missed-alarm recovery must never go through [reconcile]: reconcile is a
    /// full replace, so recovering one alarm that way would silently cancel
    /// every other alarm the user has set.
    let ringNowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.ringNow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      ringNowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmArg = args[0] as! NativeAlarm
        do {
          try api.ringNow(alarm: alarmArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      ringNowChannel.setMessageHandler(nil)
    }
    let cancelAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.cancelAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllChannel.setMessageHandler { _, reply in
        do {
          try api.cancelAll()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelAllChannel.setMessageHandler(nil)
    }
    let getPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.getPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPermissionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPermissions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPermissionsChannel.setMessageHandler(nil)
    }
    let requestNotificationPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.requestNotificationPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestNotificationPermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestNotificationPermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestNotificationPermissionChannel.setMessageHandler(nil)
    }
    let openExactAlarmSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.openExactAlarmSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openExactAlarmSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openExactAlarmSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openExactAlarmSettingsChannel.setMessageHandler(nil)
    }
    let openBatterySettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.openBatterySettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openBatterySettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openBatterySettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openBatterySettingsChannel.setMessageHandler(nil)
    }
    let openFullScreenIntentSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.openFullScreenIntentSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openFullScreenIntentSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openFullScreenIntentSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openFullScreenIntentSettingsChannel.setMessageHandler(nil)
    }
    /// The alarm id currently ringing, consumed exactly once. Covers cold start:
    /// the ringing activity can launch the Flutter engine from scratch.
    let consumeFiredAlarmIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.consumeFiredAlarmId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      consumeFiredAlarmIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.consumeFiredAlarmId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      consumeFiredAlarmIdChannel.setMessageHandler(nil)
    }
    let stopRingingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rise.AlarmHostApi.stopRinging\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRingingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmIdArg = args[0] as! Int64
        do {
          try api.stopRinging(alarmId: alarmIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopRingingChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AlarmFlutterApiProtocol {
  /// Fired when an alarm starts ringing while the engine is already alive.
  func onAlarmFired(alarmId alarmIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AlarmFlutterApi: AlarmFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AlarmApiPigeonCodec {
    return AlarmApiPigeonCodec.shared
  }
  /// Fired when an alarm starts ringing while the engine is already alive.
  func onAlarmFired(alarmId alarmIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rise.AlarmFlutterApi.onAlarmFired\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([alarmIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
