// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// One concrete future firing, as handed to the platform scheduler.
/// [fireAtEpochMs] is absolute UTC milliseconds — all wall-clock and DST
/// reasoning happens in Dart before this crosses the channel.
class NativeAlarm {
  NativeAlarm({
    required this.id,
    required this.fireAtEpochMs,
    required this.label,
    required this.soundAsset,
    required this.vibrate,
    required this.vibrationPattern,
    required this.hour,
    required this.minute,
    required this.weekdays,
  });

  int id;

  int fireAtEpochMs;

  String label;

  String soundAsset;

  bool vibrate;

  /// Vibration pattern key: 'gentle' | 'standard' | 'intense'. Only meaningful
  /// while [vibrate] is true. Unknown values fall back to 'standard' on the
  /// platform side, so a newer Dart never breaks an older native build.
  /// iOS ignores this — notification vibration is not customizable there.
  String vibrationPattern;

  /// Recurrence pattern, for platforms that own recurrence natively (iOS
  /// AlarmKit / UNCalendar). [weekdays] uses 0=Sun…6=Sat; empty = one-shot.
  /// Android ignores these and schedules the single [fireAtEpochMs] instant.
  int hour;

  int minute;

  List<int> weekdays;

  List<Object?> _toList() {
    return <Object?>[
      id,
      fireAtEpochMs,
      label,
      soundAsset,
      vibrate,
      vibrationPattern,
      hour,
      minute,
      weekdays,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAlarm decode(Object result) {
    result as List<Object?>;
    return NativeAlarm(
      id: result[0]! as int,
      fireAtEpochMs: result[1]! as int,
      label: result[2]! as String,
      soundAsset: result[3]! as String,
      vibrate: result[4]! as bool,
      vibrationPattern: result[5]! as String,
      hour: result[6]! as int,
      minute: result[7]! as int,
      weekdays: (result[8]! as List<Object?>).cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAlarm || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(fireAtEpochMs, other.fireAtEpochMs) && _deepEquals(label, other.label) && _deepEquals(soundAsset, other.soundAsset) && _deepEquals(vibrate, other.vibrate) && _deepEquals(vibrationPattern, other.vibrationPattern) && _deepEquals(hour, other.hour) && _deepEquals(minute, other.minute) && _deepEquals(weekdays, other.weekdays);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Everything that can silently stop Rise from ringing. Surfaced by the Setup
/// Guardian; re-checked on every app launch because OEMs revert these.
class AlarmPermissions {
  AlarmPermissions({
    required this.notifications,
    required this.exactAlarm,
    required this.fullScreenIntent,
    required this.batteryUnrestricted,
  });

  bool notifications;

  bool exactAlarm;

  bool fullScreenIntent;

  bool batteryUnrestricted;

  List<Object?> _toList() {
    return <Object?>[
      notifications,
      exactAlarm,
      fullScreenIntent,
      batteryUnrestricted,
    ];
  }

  Object encode() {
    return _toList();  }

  static AlarmPermissions decode(Object result) {
    result as List<Object?>;
    return AlarmPermissions(
      notifications: result[0]! as bool,
      exactAlarm: result[1]! as bool,
      fullScreenIntent: result[2]! as bool,
      batteryUnrestricted: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AlarmPermissions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(notifications, other.notifications) && _deepEquals(exactAlarm, other.exactAlarm) && _deepEquals(fullScreenIntent, other.fullScreenIntent) && _deepEquals(batteryUnrestricted, other.batteryUnrestricted);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// What a platform's alarm engine can do. iOS 16–25 has no system-alarm API,
/// so the sync service falls back to a notification burst there.
class PlatformCapabilities {
  PlatformCapabilities({
    required this.supportsSystemAlarms,
  });

  /// True when the platform can schedule true system alarms (Android
  /// AlarmManager always; iOS only on 26+ via AlarmKit). False on iOS 16–25,
  /// where [AlarmHostApi.reconcileNotifications] is used instead.
  bool supportsSystemAlarms;

  List<Object?> _toList() {
    return <Object?>[
      supportsSystemAlarms,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCapabilities decode(Object result) {
    result as List<Object?>;
    return PlatformCapabilities(
      supportsSystemAlarms: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(supportsSystemAlarms, other.supportsSystemAlarms);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// One scheduled local notification in the iOS 16–25 fallback burst. The Dart
/// budget allocator produces these; only the iOS notification engine consumes
/// them. Android reports [PlatformCapabilities.supportsSystemAlarms] true and
/// never receives these.
class NotificationRequest {
  NotificationRequest({
    required this.alarmId,
    required this.fireAtEpochMs,
    required this.label,
    required this.sound,
    required this.burstIndex,
    required this.burstTotal,
  });

  int alarmId;

  int fireAtEpochMs;

  String label;

  String sound;

  int burstIndex;

  int burstTotal;

  List<Object?> _toList() {
    return <Object?>[
      alarmId,
      fireAtEpochMs,
      label,
      sound,
      burstIndex,
      burstTotal,
    ];
  }

  Object encode() {
    return _toList();  }

  static NotificationRequest decode(Object result) {
    result as List<Object?>;
    return NotificationRequest(
      alarmId: result[0]! as int,
      fireAtEpochMs: result[1]! as int,
      label: result[2]! as String,
      sound: result[3]! as String,
      burstIndex: result[4]! as int,
      burstTotal: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alarmId, other.alarmId) && _deepEquals(fireAtEpochMs, other.fireAtEpochMs) && _deepEquals(label, other.label) && _deepEquals(sound, other.sound) && _deepEquals(burstIndex, other.burstIndex) && _deepEquals(burstTotal, other.burstTotal);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeAlarm) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AlarmPermissions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCapabilities) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NotificationRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeAlarm.decode(readValue(buffer)!);
      case 130:
        return AlarmPermissions.decode(readValue(buffer)!);
      case 131:
        return PlatformCapabilities.decode(readValue(buffer)!);
      case 132:
        return NotificationRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AlarmHostApi {
  /// Constructor for [AlarmHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AlarmHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Replaces the platform's entire scheduled set with [alarms].
  Future<void> reconcile(List<NativeAlarm> alarms) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.reconcile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alarms]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Rings [alarm] immediately without touching the scheduled set.
  ///
  /// Missed-alarm recovery must never go through [reconcile]: reconcile is a
  /// full replace, so recovering one alarm that way would silently cancel
  /// every other alarm the user has set.
  Future<void> ringNow(NativeAlarm alarm) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.ringNow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alarm]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelAll() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.cancelAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AlarmPermissions> getPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.getPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AlarmPermissions;
  }

  Future<void> requestNotificationPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.requestNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openExactAlarmSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.openExactAlarmSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openBatterySettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.openBatterySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openFullScreenIntentSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.openFullScreenIntentSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// The alarm id currently ringing, or null if nothing is ringing.
  ///
  /// Safe to call repeatedly — this peeks, it does not clear state. The id
  /// stays valid for the whole ring so [stopRinging] can verify it is
  /// stopping the alarm it was asked to stop. This is the *only* way Dart
  /// learns what is ringing — there is no push channel the other way — so
  /// callers must poll it: at cold start (the ringing activity can launch
  /// the Flutter engine from scratch) and again on every app resume (the
  /// ringing activity is `singleInstance`, so a second alarm taking over an
  /// already-running engine delivers onNewIntent natively with no signal
  /// that reaches Dart on its own).
  Future<int?> getRingingAlarmId() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.getRingingAlarmId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as int?;
  }

  Future<void> stopRinging(int alarmId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.stopRinging$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alarmId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Signals that a headless reconcile (boot, app update, clock change) has
  /// finished, so the platform can tear down the engine that ran it.
  /// Harmless to call from a normal app engine, where it is a no-op.
  Future<void> reconcileFinished() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.reconcileFinished$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// What this platform's alarm engine supports. Queried by the sync service
  /// to choose between system alarms and the notification-burst fallback.
  Future<PlatformCapabilities> capabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.capabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformCapabilities;
  }

  /// Replaces the platform's entire scheduled notification set (the iOS 16–25
  /// fallback). A full replace, like [reconcile]. No-op on Android.
  Future<void> reconcileNotifications(List<NotificationRequest> requests) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.reconcileNotifications$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requests]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Schedules the post-dismissal "still up?" check for [alarm]: a notification
  /// at [checkAtEpochMs] (absolute UTC ms) and, if the user does not confirm
  /// within 100s, a re-fire of [alarm] through the normal ring path. Android
  /// only for now; a no-op on platforms without the impl.
  Future<void> scheduleWakeCheck(NativeAlarm alarm, int checkAtEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.scheduleWakeCheck$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alarm, checkAtEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Cancels any pending wake-check (notification + re-fire) for [alarmId].
  Future<void> cancelWakeCheck(int alarmId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.cancelWakeCheck$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alarmId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Arms the nightly wind-down reminder: a plain notification (its own
  /// low-stakes channel/category — never the alarm channel) every day at
  /// [hour]:[minute] local time with the given [title]/[body]. Replaces any
  /// previously scheduled bedtime reminder. Purely a reminder: missing it has
  /// no effect on alarms.
  Future<void> scheduleBedtimeReminder(int hour, int minute, String title, String body) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.scheduleBedtimeReminder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[hour, minute, title, body]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Cancels the nightly wind-down reminder. Safe to call when none is armed.
  Future<void> cancelBedtimeReminder() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.rise.AlarmHostApi.cancelBedtimeReminder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
