// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.riseapp.rise

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AlarmApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * One concrete future firing, as handed to the platform scheduler.
 * [fireAtEpochMs] is absolute UTC milliseconds — all wall-clock and DST
 * reasoning happens in Dart before this crosses the channel.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAlarm (
  val id: Long,
  val fireAtEpochMs: Long,
  val label: String,
  val soundAsset: String,
  val vibrate: Boolean,
  /**
   * Vibration pattern key: 'gentle' | 'standard' | 'intense'. Only meaningful
   * while [vibrate] is true. Unknown values fall back to 'standard' on the
   * platform side, so a newer Dart never breaks an older native build.
   * iOS ignores this — notification vibration is not customizable there.
   */
  val vibrationPattern: String,
  /**
   * Recurrence pattern, for platforms that own recurrence natively (iOS
   * AlarmKit / UNCalendar). [weekdays] uses 0=Sun…6=Sat; empty = one-shot.
   * Android ignores these and schedules the single [fireAtEpochMs] instant.
   */
  val hour: Long,
  val minute: Long,
  val weekdays: List<Long>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAlarm {
      val id = pigeonVar_list[0] as Long
      val fireAtEpochMs = pigeonVar_list[1] as Long
      val label = pigeonVar_list[2] as String
      val soundAsset = pigeonVar_list[3] as String
      val vibrate = pigeonVar_list[4] as Boolean
      val vibrationPattern = pigeonVar_list[5] as String
      val hour = pigeonVar_list[6] as Long
      val minute = pigeonVar_list[7] as Long
      val weekdays = pigeonVar_list[8] as List<Long>
      return NativeAlarm(id, fireAtEpochMs, label, soundAsset, vibrate, vibrationPattern, hour, minute, weekdays)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      fireAtEpochMs,
      label,
      soundAsset,
      vibrate,
      vibrationPattern,
      hour,
      minute,
      weekdays,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAlarm
    return AlarmApiPigeonUtils.deepEquals(this.id, other.id) && AlarmApiPigeonUtils.deepEquals(this.fireAtEpochMs, other.fireAtEpochMs) && AlarmApiPigeonUtils.deepEquals(this.label, other.label) && AlarmApiPigeonUtils.deepEquals(this.soundAsset, other.soundAsset) && AlarmApiPigeonUtils.deepEquals(this.vibrate, other.vibrate) && AlarmApiPigeonUtils.deepEquals(this.vibrationPattern, other.vibrationPattern) && AlarmApiPigeonUtils.deepEquals(this.hour, other.hour) && AlarmApiPigeonUtils.deepEquals(this.minute, other.minute) && AlarmApiPigeonUtils.deepEquals(this.weekdays, other.weekdays)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.id)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.fireAtEpochMs)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.label)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.soundAsset)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.vibrate)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.vibrationPattern)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.hour)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.minute)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.weekdays)
    return result
  }
}

/**
 * Everything that can silently stop Rise from ringing. Surfaced by the Setup
 * Guardian; re-checked on every app launch because OEMs revert these.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AlarmPermissions (
  val notifications: Boolean,
  val exactAlarm: Boolean,
  val fullScreenIntent: Boolean,
  val batteryUnrestricted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AlarmPermissions {
      val notifications = pigeonVar_list[0] as Boolean
      val exactAlarm = pigeonVar_list[1] as Boolean
      val fullScreenIntent = pigeonVar_list[2] as Boolean
      val batteryUnrestricted = pigeonVar_list[3] as Boolean
      return AlarmPermissions(notifications, exactAlarm, fullScreenIntent, batteryUnrestricted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      notifications,
      exactAlarm,
      fullScreenIntent,
      batteryUnrestricted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AlarmPermissions
    return AlarmApiPigeonUtils.deepEquals(this.notifications, other.notifications) && AlarmApiPigeonUtils.deepEquals(this.exactAlarm, other.exactAlarm) && AlarmApiPigeonUtils.deepEquals(this.fullScreenIntent, other.fullScreenIntent) && AlarmApiPigeonUtils.deepEquals(this.batteryUnrestricted, other.batteryUnrestricted)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.notifications)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.exactAlarm)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.fullScreenIntent)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.batteryUnrestricted)
    return result
  }
}

/**
 * What a platform's alarm engine can do. iOS 16–25 has no system-alarm API,
 * so the sync service falls back to a notification burst there.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformCapabilities (
  /**
   * True when the platform can schedule true system alarms (Android
   * AlarmManager always; iOS only on 26+ via AlarmKit). False on iOS 16–25,
   * where [AlarmHostApi.reconcileNotifications] is used instead.
   */
  val supportsSystemAlarms: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCapabilities {
      val supportsSystemAlarms = pigeonVar_list[0] as Boolean
      return PlatformCapabilities(supportsSystemAlarms)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportsSystemAlarms,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformCapabilities
    return AlarmApiPigeonUtils.deepEquals(this.supportsSystemAlarms, other.supportsSystemAlarms)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.supportsSystemAlarms)
    return result
  }
}

/**
 * One scheduled local notification in the iOS 16–25 fallback burst. The Dart
 * budget allocator produces these; only the iOS notification engine consumes
 * them. Android reports [PlatformCapabilities.supportsSystemAlarms] true and
 * never receives these.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NotificationRequest (
  val alarmId: Long,
  val fireAtEpochMs: Long,
  val label: String,
  val sound: String,
  val burstIndex: Long,
  val burstTotal: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationRequest {
      val alarmId = pigeonVar_list[0] as Long
      val fireAtEpochMs = pigeonVar_list[1] as Long
      val label = pigeonVar_list[2] as String
      val sound = pigeonVar_list[3] as String
      val burstIndex = pigeonVar_list[4] as Long
      val burstTotal = pigeonVar_list[5] as Long
      return NotificationRequest(alarmId, fireAtEpochMs, label, sound, burstIndex, burstTotal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alarmId,
      fireAtEpochMs,
      label,
      sound,
      burstIndex,
      burstTotal,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationRequest
    return AlarmApiPigeonUtils.deepEquals(this.alarmId, other.alarmId) && AlarmApiPigeonUtils.deepEquals(this.fireAtEpochMs, other.fireAtEpochMs) && AlarmApiPigeonUtils.deepEquals(this.label, other.label) && AlarmApiPigeonUtils.deepEquals(this.sound, other.sound) && AlarmApiPigeonUtils.deepEquals(this.burstIndex, other.burstIndex) && AlarmApiPigeonUtils.deepEquals(this.burstTotal, other.burstTotal)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.alarmId)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.fireAtEpochMs)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.label)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.sound)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.burstIndex)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.burstTotal)
    return result
  }
}
private open class AlarmApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAlarm.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AlarmPermissions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCapabilities.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeAlarm -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AlarmPermissions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PlatformCapabilities -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NotificationRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AlarmHostApi {
  /** Replaces the platform's entire scheduled set with [alarms]. */
  fun reconcile(alarms: List<NativeAlarm>)
  /**
   * Rings [alarm] immediately without touching the scheduled set.
   *
   * Missed-alarm recovery must never go through [reconcile]: reconcile is a
   * full replace, so recovering one alarm that way would silently cancel
   * every other alarm the user has set.
   */
  fun ringNow(alarm: NativeAlarm)
  fun cancelAll()
  fun getPermissions(): AlarmPermissions
  fun requestNotificationPermission()
  fun openExactAlarmSettings()
  fun openBatterySettings()
  fun openFullScreenIntentSettings()
  /**
   * The alarm id currently ringing, or null if nothing is ringing.
   *
   * Safe to call repeatedly — this peeks, it does not clear state. The id
   * stays valid for the whole ring so [stopRinging] can verify it is
   * stopping the alarm it was asked to stop. This is the *only* way Dart
   * learns what is ringing — there is no push channel the other way — so
   * callers must poll it: at cold start (the ringing activity can launch
   * the Flutter engine from scratch) and again on every app resume (the
   * ringing activity is `singleInstance`, so a second alarm taking over an
   * already-running engine delivers onNewIntent natively with no signal
   * that reaches Dart on its own).
   */
  fun getRingingAlarmId(): Long?
  fun stopRinging(alarmId: Long)
  /**
   * Signals that a headless reconcile (boot, app update, clock change) has
   * finished, so the platform can tear down the engine that ran it.
   * Harmless to call from a normal app engine, where it is a no-op.
   */
  fun reconcileFinished()
  /**
   * What this platform's alarm engine supports. Queried by the sync service
   * to choose between system alarms and the notification-burst fallback.
   */
  fun capabilities(): PlatformCapabilities
  /**
   * Replaces the platform's entire scheduled notification set (the iOS 16–25
   * fallback). A full replace, like [reconcile]. No-op on Android.
   */
  fun reconcileNotifications(requests: List<NotificationRequest>)
  /**
   * Schedules the post-dismissal "still up?" check for [alarm]: a notification
   * at [checkAtEpochMs] (absolute UTC ms) and, if the user does not confirm
   * within 100s, a re-fire of [alarm] through the normal ring path. Android
   * only for now; a no-op on platforms without the impl.
   */
  fun scheduleWakeCheck(alarm: NativeAlarm, checkAtEpochMs: Long)
  /** Cancels any pending wake-check (notification + re-fire) for [alarmId]. */
  fun cancelWakeCheck(alarmId: Long)
  /**
   * Arms the nightly wind-down reminder: a plain notification (its own
   * low-stakes channel/category — never the alarm channel) every day at
   * [hour]:[minute] local time with the given [title]/[body]. Replaces any
   * previously scheduled bedtime reminder. Purely a reminder: missing it has
   * no effect on alarms.
   */
  fun scheduleBedtimeReminder(hour: Long, minute: Long, title: String, body: String)
  /** Cancels the nightly wind-down reminder. Safe to call when none is armed. */
  fun cancelBedtimeReminder()

  companion object {
    /** The codec used by AlarmHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AlarmApiPigeonCodec()
    }
    /** Sets up an instance of `AlarmHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AlarmHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.reconcile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmsArg = args[0] as List<NativeAlarm>
            val wrapped: List<Any?> = try {
              api.reconcile(alarmsArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.ringNow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmArg = args[0] as NativeAlarm
            val wrapped: List<Any?> = try {
              api.ringNow(alarmArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelAll()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.getPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPermissions())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestNotificationPermission()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.openExactAlarmSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openExactAlarmSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.openBatterySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openBatterySettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.openFullScreenIntentSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openFullScreenIntentSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.getRingingAlarmId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRingingAlarmId())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.stopRinging$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.stopRinging(alarmIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.reconcileFinished$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.reconcileFinished()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.capabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.capabilities())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.reconcileNotifications$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestsArg = args[0] as List<NotificationRequest>
            val wrapped: List<Any?> = try {
              api.reconcileNotifications(requestsArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.scheduleWakeCheck$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmArg = args[0] as NativeAlarm
            val checkAtEpochMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.scheduleWakeCheck(alarmArg, checkAtEpochMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.cancelWakeCheck$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelWakeCheck(alarmIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.scheduleBedtimeReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hourArg = args[0] as Long
            val minuteArg = args[1] as Long
            val titleArg = args[2] as String
            val bodyArg = args[3] as String
            val wrapped: List<Any?> = try {
              api.scheduleBedtimeReminder(hourArg, minuteArg, titleArg, bodyArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.cancelBedtimeReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelBedtimeReminder()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
