// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.riseapp.rise

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AlarmApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * One concrete future firing, as handed to the platform scheduler.
 * [fireAtEpochMs] is absolute UTC milliseconds — all wall-clock and DST
 * reasoning happens in Dart before this crosses the channel.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAlarm (
  val id: Long,
  val fireAtEpochMs: Long,
  val label: String,
  val soundAsset: String,
  val vibrate: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAlarm {
      val id = pigeonVar_list[0] as Long
      val fireAtEpochMs = pigeonVar_list[1] as Long
      val label = pigeonVar_list[2] as String
      val soundAsset = pigeonVar_list[3] as String
      val vibrate = pigeonVar_list[4] as Boolean
      return NativeAlarm(id, fireAtEpochMs, label, soundAsset, vibrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      fireAtEpochMs,
      label,
      soundAsset,
      vibrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAlarm
    return AlarmApiPigeonUtils.deepEquals(this.id, other.id) && AlarmApiPigeonUtils.deepEquals(this.fireAtEpochMs, other.fireAtEpochMs) && AlarmApiPigeonUtils.deepEquals(this.label, other.label) && AlarmApiPigeonUtils.deepEquals(this.soundAsset, other.soundAsset) && AlarmApiPigeonUtils.deepEquals(this.vibrate, other.vibrate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.id)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.fireAtEpochMs)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.label)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.soundAsset)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.vibrate)
    return result
  }
}

/**
 * Everything that can silently stop Rise from ringing. Surfaced by the Setup
 * Guardian; re-checked on every app launch because OEMs revert these.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AlarmPermissions (
  val notifications: Boolean,
  val exactAlarm: Boolean,
  val fullScreenIntent: Boolean,
  val batteryUnrestricted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AlarmPermissions {
      val notifications = pigeonVar_list[0] as Boolean
      val exactAlarm = pigeonVar_list[1] as Boolean
      val fullScreenIntent = pigeonVar_list[2] as Boolean
      val batteryUnrestricted = pigeonVar_list[3] as Boolean
      return AlarmPermissions(notifications, exactAlarm, fullScreenIntent, batteryUnrestricted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      notifications,
      exactAlarm,
      fullScreenIntent,
      batteryUnrestricted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AlarmPermissions
    return AlarmApiPigeonUtils.deepEquals(this.notifications, other.notifications) && AlarmApiPigeonUtils.deepEquals(this.exactAlarm, other.exactAlarm) && AlarmApiPigeonUtils.deepEquals(this.fullScreenIntent, other.fullScreenIntent) && AlarmApiPigeonUtils.deepEquals(this.batteryUnrestricted, other.batteryUnrestricted)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.notifications)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.exactAlarm)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.fullScreenIntent)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.batteryUnrestricted)
    return result
  }
}
private open class AlarmApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAlarm.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AlarmPermissions.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeAlarm -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AlarmPermissions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AlarmHostApi {
  /** Replaces the platform's entire scheduled set with [alarms]. */
  fun reconcile(alarms: List<NativeAlarm>)
  /**
   * Rings [alarm] immediately without touching the scheduled set.
   *
   * Missed-alarm recovery must never go through [reconcile]: reconcile is a
   * full replace, so recovering one alarm that way would silently cancel
   * every other alarm the user has set.
   */
  fun ringNow(alarm: NativeAlarm)
  fun cancelAll()
  fun getPermissions(): AlarmPermissions
  fun requestNotificationPermission()
  fun openExactAlarmSettings()
  fun openBatterySettings()
  fun openFullScreenIntentSettings()
  /**
   * The alarm id currently ringing, or null if nothing is ringing.
   *
   * Safe to call repeatedly — this peeks, it does not clear state. The id
   * stays valid for the whole ring so [stopRinging] can verify it is
   * stopping the alarm it was asked to stop. Needed at cold start: the
   * ringing activity can launch the Flutter engine from scratch, in which
   * case no onAlarmFired callback ever arrives.
   */
  fun getRingingAlarmId(): Long?
  fun stopRinging(alarmId: Long)
  /**
   * Signals that a headless reconcile (boot, app update, clock change) has
   * finished, so the platform can tear down the engine that ran it.
   * Harmless to call from a normal app engine, where it is a no-op.
   */
  fun reconcileFinished()

  companion object {
    /** The codec used by AlarmHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AlarmApiPigeonCodec()
    }
    /** Sets up an instance of `AlarmHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AlarmHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.reconcile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmsArg = args[0] as List<NativeAlarm>
            val wrapped: List<Any?> = try {
              api.reconcile(alarmsArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.ringNow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmArg = args[0] as NativeAlarm
            val wrapped: List<Any?> = try {
              api.ringNow(alarmArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelAll()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.getPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPermissions())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestNotificationPermission()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.openExactAlarmSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openExactAlarmSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.openBatterySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openBatterySettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.openFullScreenIntentSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openFullScreenIntentSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.getRingingAlarmId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRingingAlarmId())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.stopRinging$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.stopRinging(alarmIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rise.AlarmHostApi.reconcileFinished$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.reconcileFinished()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AlarmFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AlarmFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      AlarmApiPigeonCodec()
    }
  }
  /** Fired when an alarm starts ringing while the engine is already alive. */
  fun onAlarmFired(alarmIdArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rise.AlarmFlutterApi.onAlarmFired$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(alarmIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AlarmApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
